In [2]:
 import torch

In [9]:
#keep the values constant in each run
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [16]:
#different values at each iteration
torch.rand(2,3)

tensor([[0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895]])

In [18]:
#arrange we give step size
torch.arange(5,15,2)

tensor([ 5,  7,  9, 11, 13])

In [20]:
#linspace u give no.of elements
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [21]:
#identity matrix (eye)
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
#diagonal matrix
torch.diag(torch.tensor([1,2,3,5]))

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 5]])

In [23]:
#full
torch.full((4,5),7)

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])

In [26]:
var1 = torch.tensor([1,2,3],dtype = torch.int64)
var1

tensor([1, 2, 3])

In [27]:
var1 = torch.tensor([1,2,3],dtype = torch.float64)
var1

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
var1.shape

torch.Size([3])

In [30]:
var1.ndim

1

In [32]:
var1.reshape(3)

tensor([1., 2., 3.], dtype=torch.float64)

In [33]:
var1.flatten()

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
mat1 = torch.tensor(([1,2,3],[5,3,1.0]))
mat1

tensor([[1., 2., 3.],
        [5., 3., 1.]])

In [35]:
mat2 = torch.tensor(([0,2,1],[4,1,1.0]))
mat2

tensor([[0., 2., 1.],
        [4., 1., 1.]])

In [36]:
mat1+mat2

tensor([[1., 4., 4.],
        [9., 4., 2.]])

In [37]:
mat1-mat2

tensor([[1., 0., 2.],
        [1., 2., 0.]])

In [38]:
mat1**mat2

tensor([[  1.,   4.,   3.],
        [625.,   3.,   1.]])

In [39]:
mat3 = torch.rand(2,3)
mat3

tensor([[0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103]])

In [40]:
torch.floor(mat3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [41]:
torch.ceil(mat3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [42]:
torch.round(mat3)

tensor([[1., 0., 0.],
        [0., 0., 1.]])

In [43]:
mat2.sum()

tensor(9.)

In [44]:
mat2.sum(axis=0)#or 1

tensor([4., 3., 2.])

In [45]:
mat2.mean()

tensor(1.5000)

In [46]:
mat2.median()

tensor(1.)

In [48]:
torch.matmul(mat1.T,mat2)

tensor([[20.,  7.,  6.],
        [12.,  7.,  5.],
        [ 4.,  7.,  4.]])

In [49]:
mat1>mat2

tensor([[ True, False,  True],
        [ True,  True, False]])

In [51]:
torch.log(torch.tensor([1,2,3]))

tensor([0.0000, 0.6931, 1.0986])

In [52]:
torch.exp(torch.tensor([1,2,3]))

tensor([ 2.7183,  7.3891, 20.0855])